"""create posts table

Revision ID: 722d3b423c1d
Revises: d4cfa1f3b14b
Create Date: 2024-05-06 04:45:05.467660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722d3b423c1d'
down_revision: Union[str, None] = 'd4cfa1f3b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
